version: '3'

services:
  server:
    container_name: server
    restart: always
    build: .
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
      # - ${DB_LOG_DIR}:/usr/src/app/database/logs/
    depends_on: [hangar_db]
    links:
      - hangar_db
    command: ${COMMAND_PARAMS}
    # command: ["npm", "start"]
    # command: ["npm", "run", "build"]
  hangar_db:
    container_name: hangar_db
    image: mongo:4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - APP_MONGO_HOST=${DB_HOST}
      - MONGO_PORT=${DB_PORT}
      - MONGO_ROOT_USER=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASS=${MONGO_ROOT_PASSWORD}
      - APP_MONGO_USER=${DB_USER}
      - APP_MONGO_PASS=${DB_PASSWORD}
      - APP_MONGO_DB=${DB_NAME}
      - TEST_MONGO_DB=${DB_TEST_NAME}
      - TEST_MONGO_USER=${DB_TEST_USER}
      - TEST_MONGO_PASS=${DB_TEST_PASS}
    # user: ${CURRENT_UID}
    restart: always
    volumes:
      - ${DB_DATA_DIR}:/data/db
      - ${DB_TEST_DIR}:/test/db
      # - ${DB_LOG_DIR}:/var/log/
      - ./database/scripts:/docker-entrypoint-initdb.d/
    ports:
      - "27017:27017"
    command: "mongod --smallfiles"
