version: '3.5'

services:

  hangar_nginx:
    ports:
      - "80:4000"
      - "443:443"

    volumes:
      - web-root:/var/www/html
      - ./src/config/nginx/conf-https:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./web_root/dhparam:/etc/ssl/certs