version: '3'

services:
  hangar_server:
    container_name: hangar_server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - hangar-network
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    depends_on: [hangar_db]
    links:
      - hangar_db
    command: ${COMMAND_PARAMS}

  hangar_db:
    container_name: hangar_db
    image: mongo:4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - APP_MONGO_HOST=${DB_HOST}
      - MONGO_PORT=${DB_PORT}
      - MONGO_ROOT_USER=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASS=${MONGO_ROOT_PASSWORD}
      - APP_MONGO_USER=${DB_USER}
      - APP_MONGO_PASS=${DB_PASSWORD}
      - APP_MONGO_DB=${DB_NAME}
      - TEST_MONGO_DB=${DB_TEST_NAME}
      - TEST_MONGO_USER=${DB_TEST_USER}
      - TEST_MONGO_PASS=${DB_TEST_PASS}
    restart: always
    volumes:
      - ${DB_DATA_DIR}:/data/db
      - ${DB_TEST_DIR}:/test/db
      - ./database/scripts:/docker-entrypoint-initdb.d/
    ports:
      - "27017:27017"
    networks:
      - hangar-network
    command: "mongod --smallfiles"

networks:
  hangar-network:
    driver: bridge

volumes:
  certbot-etc:
  certbot-var:
  web-root:
