version: '3.5'

services:
  certbot:
      image: certbot/certbot
      container_name: hangar_certbot
      volumes:
        - certbot-etc:/etc/letsencrypt
        - certbot-var:/var/lib/letsencrypt
        - web-root:/var/www/html
      depends_on:
        - hangar_nginx
      # command: certonly --webroot --webroot-path=/var/www/html --email ${DOMAIN_EMAIL} --agree-tos --no-eff-email --staging -d ${APP_DOMAIN} -d www.${APP_DOMAIN}