version: '3.5'

services:
  hangar_server:
    container_name: hangar_server
    restart: always
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile

    networks:
      - hangar-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
      - web-root:/var/www/html
    depends_on: [hangar_db]
    links:
      - hangar_db
    command: ./wait-for-it.sh hangar_db:27017 -- ${COMMAND_PARAMS}

  hangar_db:
    container_name: hangar_db
    image: mongo:4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - APP_MONGO_HOST=${DB_HOST}
      - MONGO_PORT=${DB_PORT}
      - MONGO_ROOT_USER=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASS=${MONGO_ROOT_PASSWORD}
      - APP_MONGO_USER=${DB_USER}
      - APP_MONGO_PASS=${DB_PASSWORD}
      - APP_MONGO_DB=${DB_NAME}
      - TEST_MONGO_DB=${DB_TEST_NAME}
      - TEST_MONGO_USER=${DB_TEST_USER}
      - TEST_MONGO_PASS=${DB_TEST_PASS}
    restart: always
    volumes:
      - ${DB_DATA_DIR}:/data/db
      - ${DB_TEST_DIR}:/test/db
      - ./database/scripts:/docker-entrypoint-initdb.d/
    ports:
      - "27017:27017"
    networks:
      - hangar-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "27017"]
      timeout: 10s
      interval: 10s
      retries: 10
    command: "mongod --smallfiles"

  hangar_nginx:
    image: nginx:mainline-alpine
    container_name: hangar_nginx
    restart: unless-stopped
    ports:
      - "80:4000"
      #- "443:443"
    environment:
      - APP_DOMAIN=${APP_DOMAIN}

    volumes:
      - web-root:/var/www/html
      - ./src/config/nginx/conf-http:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs

    depends_on: [hangar_server]
    networks:
      - hangar-network

networks:
  hangar-network:
    driver: bridge

volumes:
  certbot-etc:
    driver: local
    driver_opts:
      type: none
      device: $PWD/ssl_cert/etc
      o: bind
  certbot-var:
    driver: local
    driver_opts:
      type: none
      device: $PWD/ssl_cert/var
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: $PWD/ssl_cert/dhparam
      o: bind
  web-root:
    driver: local
    driver_opts:
      type: none
      device: $PWD/web_root
      o: bind
